name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          version: v2.1.0
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
      - uses: rhysd/action-setup-vim@v1
        with:
          version: stable
          neovim: true
      - run: ./tests/run.sh
